AWSTemplateFormatVersion: '2010-09-09'
Resources:
  HelloWorldFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'HelloWorldFunction'
      Handler: index.handler
      Runtime: nodejs14.x
      Role: 
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Code:
        ZipFile: |
          exports.handler = async(event) => {
            console.log("hello");
            const response = {
                statusCode: 200,
                body: JSON.stringify('Hello from Lambda!'),
            };
            return response;
          };
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 20

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        
  MyLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/aws/lambda/myLambdaFunction"
      RetentionInDays: 14
